/*
 * This file is generated by jOOQ.
 */
package org.jooq.your.packagename;


import java.util.Arrays;
import java.util.List;

import org.jooq.Constants;
import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;
import org.jooq.your.packagename.cht_newcomer_training.ChtNewcomerTraining;
import org.jooq.your.packagename.information_schema.InformationSchema;
import org.jooq.your.packagename.ku.Ku;
import org.jooq.your.packagename.ku_test.KuTest;
import org.jooq.your.packagename.mysql.Mysql;
import org.jooq.your.packagename.performance_schema.PerformanceSchema;
import org.jooq.your.packagename.sys.Sys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>cht_newcomer_training</code>.
     */
    public final ChtNewcomerTraining CHT_NEWCOMER_TRAINING = ChtNewcomerTraining.CHT_NEWCOMER_TRAINING;

    /**
     * The schema <code>information_schema</code>.
     */
    public final InformationSchema INFORMATION_SCHEMA = InformationSchema.INFORMATION_SCHEMA;

    /**
     * The schema <code>ku</code>.
     */
    public final Ku KU = Ku.KU;

    /**
     * The schema <code>ku_test</code>.
     */
    public final KuTest KU_TEST = KuTest.KU_TEST;

    /**
     * The schema <code>mysql</code>.
     */
    public final Mysql MYSQL = Mysql.MYSQL;

    /**
     * The schema <code>performance_schema</code>.
     */
    public final PerformanceSchema PERFORMANCE_SCHEMA = PerformanceSchema.PERFORMANCE_SCHEMA;

    /**
     * The schema <code>sys</code>.
     */
    public final Sys SYS = Sys.SYS;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.asList(
            ChtNewcomerTraining.CHT_NEWCOMER_TRAINING,
            InformationSchema.INFORMATION_SCHEMA,
            Ku.KU,
            KuTest.KU_TEST,
            Mysql.MYSQL,
            PerformanceSchema.PERFORMANCE_SCHEMA,
            Sys.SYS
        );
    }

    /**
     * A reference to the 3.18 minor release of the code generator. If this
     * doesn't compile, it's because the runtime library uses an older minor
     * release, namely: 3.18. You can turn off the generation of this reference
     * by specifying /configuration/generator/generate/jooqVersionReference
     */
    private static final String REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_18;
}
