/*
 * This file is generated by jOOQ.
 */
package cht.eric.models.cht_newcomer_training.tables;


import cht.eric.models.cht_newcomer_training.ChtNewcomerTraining;
import cht.eric.models.cht_newcomer_training.Keys;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberPrivileges extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>cht_newcomer_training.member_privileges</code>
     */
    public static final MemberPrivileges MEMBER_PRIVILEGES = new MemberPrivileges();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>cht_newcomer_training.member_privileges.id</code>.
     */
    public final TableField<Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>cht_newcomer_training.member_privileges.privilege_name</code>.
     */
    public final TableField<Record, String> PRIVILEGE_NAME = createField(DSL.name("privilege_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private MemberPrivileges(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private MemberPrivileges(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>cht_newcomer_training.member_privileges</code>
     * table reference
     */
    public MemberPrivileges(String alias) {
        this(DSL.name(alias), MEMBER_PRIVILEGES);
    }

    /**
     * Create an aliased <code>cht_newcomer_training.member_privileges</code>
     * table reference
     */
    public MemberPrivileges(Name alias) {
        this(alias, MEMBER_PRIVILEGES);
    }

    /**
     * Create a <code>cht_newcomer_training.member_privileges</code> table
     * reference
     */
    public MemberPrivileges() {
        this(DSL.name("member_privileges"), null);
    }

    public <O extends Record> MemberPrivileges(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, MEMBER_PRIVILEGES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ChtNewcomerTraining.CHT_NEWCOMER_TRAINING;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_MEMBER_PRIVILEGES_PRIMARY;
    }

    @Override
    public MemberPrivileges as(String alias) {
        return new MemberPrivileges(DSL.name(alias), this);
    }

    @Override
    public MemberPrivileges as(Name alias) {
        return new MemberPrivileges(alias, this);
    }

    @Override
    public MemberPrivileges as(Table<?> alias) {
        return new MemberPrivileges(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MemberPrivileges rename(String name) {
        return new MemberPrivileges(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MemberPrivileges rename(Name name) {
        return new MemberPrivileges(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MemberPrivileges rename(Table<?> name) {
        return new MemberPrivileges(name.getQualifiedName(), null);
    }
}
