/*
 * This file is generated by jOOQ.
 */
package cht.eric.models.cht_newcomer_training.tables;


import cht.eric.models.cht_newcomer_training.ChtNewcomerTraining;
import cht.eric.models.cht_newcomer_training.Keys;
import cht.eric.models.cht_newcomer_training.enums.OrdersRegion;
import cht.eric.models.cht_newcomer_training.enums.OrdersSegment;
import cht.eric.models.cht_newcomer_training.enums.OrdersShipMode;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cht_newcomer_training.orders</code>
     */
    public static final Orders ORDERS = new Orders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>cht_newcomer_training.orders.id</code>.
     */
    public final TableField<Record, String> ID = createField(DSL.name("id"), SQLDataType.CHAR(14).nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.order_date</code>.
     */
    public final TableField<Record, LocalDate> ORDER_DATE = createField(DSL.name("order_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.ship_date</code>.
     */
    public final TableField<Record, LocalDate> SHIP_DATE = createField(DSL.name("ship_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.ship_mode</code>.
     */
    public final TableField<Record, OrdersShipMode> SHIP_MODE = createField(DSL.name("ship_mode"), SQLDataType.VARCHAR(14).nullable(false).asEnumDataType(cht.eric.models.cht_newcomer_training.enums.OrdersShipMode.class), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.customer_id_number</code>.
     */
    public final TableField<Record, String> CUSTOMER_ID_NUMBER = createField(DSL.name("customer_id_number"), SQLDataType.CHAR(8).nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.customer_name</code>.
     */
    public final TableField<Record, String> CUSTOMER_NAME = createField(DSL.name("customer_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.segment</code>.
     */
    public final TableField<Record, OrdersSegment> SEGMENT = createField(DSL.name("segment"), SQLDataType.VARCHAR(11).nullable(false).asEnumDataType(cht.eric.models.cht_newcomer_training.enums.OrdersSegment.class), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.country</code>.
     */
    public final TableField<Record, String> COUNTRY = createField(DSL.name("country"), SQLDataType.VARCHAR(300).nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.city</code>.
     */
    public final TableField<Record, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(300).nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.state</code>.
     */
    public final TableField<Record, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(300).nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.postal_code</code>.
     */
    public final TableField<Record, Integer> POSTAL_CODE = createField(DSL.name("postal_code"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.region</code>.
     */
    public final TableField<Record, OrdersRegion> REGION = createField(DSL.name("region"), SQLDataType.VARCHAR(7).nullable(false).asEnumDataType(cht.eric.models.cht_newcomer_training.enums.OrdersRegion.class), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.product_id_number</code>.
     */
    public final TableField<Record, String> PRODUCT_ID_NUMBER = createField(DSL.name("product_id_number"), SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.category</code>.
     */
    public final TableField<Record, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.sub_category</code>.
     */
    public final TableField<Record, String> SUB_CATEGORY = createField(DSL.name("sub_category"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.product_name</code>.
     */
    public final TableField<Record, String> PRODUCT_NAME = createField(DSL.name("product_name"), SQLDataType.VARCHAR(300).nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.sales</code>.
     */
    public final TableField<Record, Double> SALES = createField(DSL.name("sales"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.quantity</code>.
     */
    public final TableField<Record, Integer> QUANTITY = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.discount</code>.
     */
    public final TableField<Record, Double> DISCOUNT = createField(DSL.name("discount"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.profit</code>.
     */
    public final TableField<Record, Double> PROFIT = createField(DSL.name("profit"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>cht_newcomer_training.orders.is_returned</code>.
     */
    public final TableField<Record, Byte> IS_RETURNED = createField(DSL.name("is_returned"), SQLDataType.TINYINT.nullable(false), this, "");

    private Orders(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Orders(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>cht_newcomer_training.orders</code> table
     * reference
     */
    public Orders(String alias) {
        this(DSL.name(alias), ORDERS);
    }

    /**
     * Create an aliased <code>cht_newcomer_training.orders</code> table
     * reference
     */
    public Orders(Name alias) {
        this(alias, ORDERS);
    }

    /**
     * Create a <code>cht_newcomer_training.orders</code> table reference
     */
    public Orders() {
        this(DSL.name("orders"), null);
    }

    public <O extends Record> Orders(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, ORDERS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ChtNewcomerTraining.CHT_NEWCOMER_TRAINING;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_ORDERS_PRIMARY;
    }

    @Override
    public Orders as(String alias) {
        return new Orders(DSL.name(alias), this);
    }

    @Override
    public Orders as(Name alias) {
        return new Orders(alias, this);
    }

    @Override
    public Orders as(Table<?> alias) {
        return new Orders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Orders rename(String name) {
        return new Orders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orders rename(Name name) {
        return new Orders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orders rename(Table<?> name) {
        return new Orders(name.getQualifiedName(), null);
    }
}
