/*
 * This file is generated by jOOQ.
 */
package cht.eric.models.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "member_privilege",
    schema = "cht_newcomer_training"
)
public class MemberPrivilege implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String privilegeName;

    public MemberPrivilege() {}

    public MemberPrivilege(MemberPrivilege value) {
        this.id = value.id;
        this.privilegeName = value.privilegeName;
    }

    public MemberPrivilege(
        Integer id,
        String privilegeName
    ) {
        this.id = id;
        this.privilegeName = privilegeName;
    }

    /**
     * Getter for <code>cht_newcomer_training.member_privilege.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    @NotNull
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>cht_newcomer_training.member_privilege.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>cht_newcomer_training.member_privilege.privilege_name</code>.
     */
    @Column(name = "privilege_name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getPrivilegeName() {
        return this.privilegeName;
    }

    /**
     * Setter for
     * <code>cht_newcomer_training.member_privilege.privilege_name</code>.
     */
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MemberPrivilege other = (MemberPrivilege) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.privilegeName == null) {
            if (other.privilegeName != null)
                return false;
        }
        else if (!this.privilegeName.equals(other.privilegeName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.privilegeName == null) ? 0 : this.privilegeName.hashCode());
        return result;
    }
}
