/*
 * This file is generated by jOOQ.
 */
package cht.eric.models.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "member",
    schema = "cht_newcomer_training",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_member_KEY_member_unq_members", columnNames = { "user_id" }),
        @UniqueConstraint(name = "KEY_member_unq_members", columnNames = { "user_id" })
    }
)
public class Member implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private Byte region;
    private Integer userId;

    public Member() {}

    public Member(Member value) {
        this.id = value.id;
        this.name = value.name;
        this.region = value.region;
        this.userId = value.userId;
    }

    public Member(
        Integer id,
        String name,
        Byte region,
        Integer userId
    ) {
        this.id = id;
        this.name = name;
        this.region = region;
        this.userId = userId;
    }

    /**
     * Getter for <code>cht_newcomer_training.member.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>cht_newcomer_training.member.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>cht_newcomer_training.member.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>cht_newcomer_training.member.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>cht_newcomer_training.member.region</code>.
     */
    @Column(name = "region", nullable = false)
    @NotNull
    public Byte getRegion() {
        return this.region;
    }

    /**
     * Setter for <code>cht_newcomer_training.member.region</code>.
     */
    public void setRegion(Byte region) {
        this.region = region;
    }

    /**
     * Getter for <code>cht_newcomer_training.member.user_id</code>.
     */
    @Column(name = "user_id", nullable = false)
    @NotNull
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>cht_newcomer_training.member.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Member other = (Member) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.region == null) {
            if (other.region != null)
                return false;
        }
        else if (!this.region.equals(other.region))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.region == null) ? 0 : this.region.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }
}
