/*
 * This file is generated by jOOQ.
 */
package org.jooq.your.packagename.cht_newcomer_training.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.your.packagename.cht_newcomer_training.tables.MemberPrivileges;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberPrivilegesRecord extends UpdatableRecordImpl<MemberPrivilegesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cht_newcomer_training.member_privileges.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.member_privileges.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>cht_newcomer_training.member_privileges.privilege_name</code>.
     */
    public void setPrivilegeName(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>cht_newcomer_training.member_privileges.privilege_name</code>.
     */
    public String getPrivilegeName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MemberPrivileges.MEMBER_PRIVILEGES.ID;
    }

    @Override
    public Field<String> field2() {
        return MemberPrivileges.MEMBER_PRIVILEGES.PRIVILEGE_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPrivilegeName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPrivilegeName();
    }

    @Override
    public MemberPrivilegesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MemberPrivilegesRecord value2(String value) {
        setPrivilegeName(value);
        return this;
    }

    @Override
    public MemberPrivilegesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberPrivilegesRecord
     */
    public MemberPrivilegesRecord() {
        super(MemberPrivileges.MEMBER_PRIVILEGES);
    }

    /**
     * Create a detached, initialised MemberPrivilegesRecord
     */
    public MemberPrivilegesRecord(Integer id, String privilegeName) {
        super(MemberPrivileges.MEMBER_PRIVILEGES);

        setId(id);
        setPrivilegeName(privilegeName);
        resetChangedOnNotNull();
    }
}
