/*
 * This file is generated by jOOQ.
 */
package org.jooq.your.packagename.cht_newcomer_training.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.your.packagename.cht_newcomer_training.enums.OrdersRegion;
import org.jooq.your.packagename.cht_newcomer_training.enums.OrdersSegment;
import org.jooq.your.packagename.cht_newcomer_training.enums.OrdersShipMode;
import org.jooq.your.packagename.cht_newcomer_training.tables.Orders;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> implements Record21<String, LocalDate, LocalDate, OrdersShipMode, String, String, OrdersSegment, String, String, String, Integer, OrdersRegion, String, String, String, String, Double, Integer, Double, Double, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cht_newcomer_training.orders.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.order_date</code>.
     */
    public void setOrderDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.order_date</code>.
     */
    public LocalDate getOrderDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.ship_date</code>.
     */
    public void setShipDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.ship_date</code>.
     */
    public LocalDate getShipDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.ship_mode</code>.
     */
    public void setShipMode(OrdersShipMode value) {
        set(3, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.ship_mode</code>.
     */
    public OrdersShipMode getShipMode() {
        return (OrdersShipMode) get(3);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.customer_id_number</code>.
     */
    public void setCustomerIdNumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.customer_id_number</code>.
     */
    public String getCustomerIdNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.customer_name</code>.
     */
    public void setCustomerName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.customer_name</code>.
     */
    public String getCustomerName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.segment</code>.
     */
    public void setSegment(OrdersSegment value) {
        set(6, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.segment</code>.
     */
    public OrdersSegment getSegment() {
        return (OrdersSegment) get(6);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.country</code>.
     */
    public void setCountry(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.country</code>.
     */
    public String getCountry() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.city</code>.
     */
    public void setCity(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.city</code>.
     */
    public String getCity() {
        return (String) get(8);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.state</code>.
     */
    public void setState(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.state</code>.
     */
    public String getState() {
        return (String) get(9);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.postal_code</code>.
     */
    public void setPostalCode(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.postal_code</code>.
     */
    public Integer getPostalCode() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.region</code>.
     */
    public void setRegion(OrdersRegion value) {
        set(11, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.region</code>.
     */
    public OrdersRegion getRegion() {
        return (OrdersRegion) get(11);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.product_id_number</code>.
     */
    public void setProductIdNumber(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.product_id_number</code>.
     */
    public String getProductIdNumber() {
        return (String) get(12);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.category</code>.
     */
    public void setCategory(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.category</code>.
     */
    public String getCategory() {
        return (String) get(13);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.sub_category</code>.
     */
    public void setSubCategory(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.sub_category</code>.
     */
    public String getSubCategory() {
        return (String) get(14);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.product_name</code>.
     */
    public void setProductName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.product_name</code>.
     */
    public String getProductName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.sales</code>.
     */
    public void setSales(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.sales</code>.
     */
    public Double getSales() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.discount</code>.
     */
    public void setDiscount(Double value) {
        set(18, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.discount</code>.
     */
    public Double getDiscount() {
        return (Double) get(18);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.profit</code>.
     */
    public void setProfit(Double value) {
        set(19, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.profit</code>.
     */
    public Double getProfit() {
        return (Double) get(19);
    }

    /**
     * Setter for <code>cht_newcomer_training.orders.is_returned</code>.
     */
    public void setIsReturned(Byte value) {
        set(20, value);
    }

    /**
     * Getter for <code>cht_newcomer_training.orders.is_returned</code>.
     */
    public Byte getIsReturned() {
        return (Byte) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<String, LocalDate, LocalDate, OrdersShipMode, String, String, OrdersSegment, String, String, String, Integer, OrdersRegion, String, String, String, String, Double, Integer, Double, Double, Byte> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<String, LocalDate, LocalDate, OrdersShipMode, String, String, OrdersSegment, String, String, String, Integer, OrdersRegion, String, String, String, String, Double, Integer, Double, Double, Byte> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Orders.ORDERS.ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return Orders.ORDERS.ORDER_DATE;
    }

    @Override
    public Field<LocalDate> field3() {
        return Orders.ORDERS.SHIP_DATE;
    }

    @Override
    public Field<OrdersShipMode> field4() {
        return Orders.ORDERS.SHIP_MODE;
    }

    @Override
    public Field<String> field5() {
        return Orders.ORDERS.CUSTOMER_ID_NUMBER;
    }

    @Override
    public Field<String> field6() {
        return Orders.ORDERS.CUSTOMER_NAME;
    }

    @Override
    public Field<OrdersSegment> field7() {
        return Orders.ORDERS.SEGMENT;
    }

    @Override
    public Field<String> field8() {
        return Orders.ORDERS.COUNTRY;
    }

    @Override
    public Field<String> field9() {
        return Orders.ORDERS.CITY;
    }

    @Override
    public Field<String> field10() {
        return Orders.ORDERS.STATE;
    }

    @Override
    public Field<Integer> field11() {
        return Orders.ORDERS.POSTAL_CODE;
    }

    @Override
    public Field<OrdersRegion> field12() {
        return Orders.ORDERS.REGION;
    }

    @Override
    public Field<String> field13() {
        return Orders.ORDERS.PRODUCT_ID_NUMBER;
    }

    @Override
    public Field<String> field14() {
        return Orders.ORDERS.CATEGORY;
    }

    @Override
    public Field<String> field15() {
        return Orders.ORDERS.SUB_CATEGORY;
    }

    @Override
    public Field<String> field16() {
        return Orders.ORDERS.PRODUCT_NAME;
    }

    @Override
    public Field<Double> field17() {
        return Orders.ORDERS.SALES;
    }

    @Override
    public Field<Integer> field18() {
        return Orders.ORDERS.QUANTITY;
    }

    @Override
    public Field<Double> field19() {
        return Orders.ORDERS.DISCOUNT;
    }

    @Override
    public Field<Double> field20() {
        return Orders.ORDERS.PROFIT;
    }

    @Override
    public Field<Byte> field21() {
        return Orders.ORDERS.IS_RETURNED;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDate component2() {
        return getOrderDate();
    }

    @Override
    public LocalDate component3() {
        return getShipDate();
    }

    @Override
    public OrdersShipMode component4() {
        return getShipMode();
    }

    @Override
    public String component5() {
        return getCustomerIdNumber();
    }

    @Override
    public String component6() {
        return getCustomerName();
    }

    @Override
    public OrdersSegment component7() {
        return getSegment();
    }

    @Override
    public String component8() {
        return getCountry();
    }

    @Override
    public String component9() {
        return getCity();
    }

    @Override
    public String component10() {
        return getState();
    }

    @Override
    public Integer component11() {
        return getPostalCode();
    }

    @Override
    public OrdersRegion component12() {
        return getRegion();
    }

    @Override
    public String component13() {
        return getProductIdNumber();
    }

    @Override
    public String component14() {
        return getCategory();
    }

    @Override
    public String component15() {
        return getSubCategory();
    }

    @Override
    public String component16() {
        return getProductName();
    }

    @Override
    public Double component17() {
        return getSales();
    }

    @Override
    public Integer component18() {
        return getQuantity();
    }

    @Override
    public Double component19() {
        return getDiscount();
    }

    @Override
    public Double component20() {
        return getProfit();
    }

    @Override
    public Byte component21() {
        return getIsReturned();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDate value2() {
        return getOrderDate();
    }

    @Override
    public LocalDate value3() {
        return getShipDate();
    }

    @Override
    public OrdersShipMode value4() {
        return getShipMode();
    }

    @Override
    public String value5() {
        return getCustomerIdNumber();
    }

    @Override
    public String value6() {
        return getCustomerName();
    }

    @Override
    public OrdersSegment value7() {
        return getSegment();
    }

    @Override
    public String value8() {
        return getCountry();
    }

    @Override
    public String value9() {
        return getCity();
    }

    @Override
    public String value10() {
        return getState();
    }

    @Override
    public Integer value11() {
        return getPostalCode();
    }

    @Override
    public OrdersRegion value12() {
        return getRegion();
    }

    @Override
    public String value13() {
        return getProductIdNumber();
    }

    @Override
    public String value14() {
        return getCategory();
    }

    @Override
    public String value15() {
        return getSubCategory();
    }

    @Override
    public String value16() {
        return getProductName();
    }

    @Override
    public Double value17() {
        return getSales();
    }

    @Override
    public Integer value18() {
        return getQuantity();
    }

    @Override
    public Double value19() {
        return getDiscount();
    }

    @Override
    public Double value20() {
        return getProfit();
    }

    @Override
    public Byte value21() {
        return getIsReturned();
    }

    @Override
    public OrdersRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public OrdersRecord value2(LocalDate value) {
        setOrderDate(value);
        return this;
    }

    @Override
    public OrdersRecord value3(LocalDate value) {
        setShipDate(value);
        return this;
    }

    @Override
    public OrdersRecord value4(OrdersShipMode value) {
        setShipMode(value);
        return this;
    }

    @Override
    public OrdersRecord value5(String value) {
        setCustomerIdNumber(value);
        return this;
    }

    @Override
    public OrdersRecord value6(String value) {
        setCustomerName(value);
        return this;
    }

    @Override
    public OrdersRecord value7(OrdersSegment value) {
        setSegment(value);
        return this;
    }

    @Override
    public OrdersRecord value8(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public OrdersRecord value9(String value) {
        setCity(value);
        return this;
    }

    @Override
    public OrdersRecord value10(String value) {
        setState(value);
        return this;
    }

    @Override
    public OrdersRecord value11(Integer value) {
        setPostalCode(value);
        return this;
    }

    @Override
    public OrdersRecord value12(OrdersRegion value) {
        setRegion(value);
        return this;
    }

    @Override
    public OrdersRecord value13(String value) {
        setProductIdNumber(value);
        return this;
    }

    @Override
    public OrdersRecord value14(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public OrdersRecord value15(String value) {
        setSubCategory(value);
        return this;
    }

    @Override
    public OrdersRecord value16(String value) {
        setProductName(value);
        return this;
    }

    @Override
    public OrdersRecord value17(Double value) {
        setSales(value);
        return this;
    }

    @Override
    public OrdersRecord value18(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public OrdersRecord value19(Double value) {
        setDiscount(value);
        return this;
    }

    @Override
    public OrdersRecord value20(Double value) {
        setProfit(value);
        return this;
    }

    @Override
    public OrdersRecord value21(Byte value) {
        setIsReturned(value);
        return this;
    }

    @Override
    public OrdersRecord values(String value1, LocalDate value2, LocalDate value3, OrdersShipMode value4, String value5, String value6, OrdersSegment value7, String value8, String value9, String value10, Integer value11, OrdersRegion value12, String value13, String value14, String value15, String value16, Double value17, Integer value18, Double value19, Double value20, Byte value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(String id, LocalDate orderDate, LocalDate shipDate, OrdersShipMode shipMode, String customerIdNumber, String customerName, OrdersSegment segment, String country, String city, String state, Integer postalCode, OrdersRegion region, String productIdNumber, String category, String subCategory, String productName, Double sales, Integer quantity, Double discount, Double profit, Byte isReturned) {
        super(Orders.ORDERS);

        setId(id);
        setOrderDate(orderDate);
        setShipDate(shipDate);
        setShipMode(shipMode);
        setCustomerIdNumber(customerIdNumber);
        setCustomerName(customerName);
        setSegment(segment);
        setCountry(country);
        setCity(city);
        setState(state);
        setPostalCode(postalCode);
        setRegion(region);
        setProductIdNumber(productIdNumber);
        setCategory(category);
        setSubCategory(subCategory);
        setProductName(productName);
        setSales(sales);
        setQuantity(quantity);
        setDiscount(discount);
        setProfit(profit);
        setIsReturned(isReturned);
        resetChangedOnNotNull();
    }
}
