package cht.eric.models;
// Generated 2023年6月19日 下午2:30:18 by Hibernate Tools 6.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * MemberPrivileges generated by hbm2java
 */
public class MemberPrivileges implements java.io.Serializable {

	private int id;
	private String privilegeName;
	private Set memberses = new HashSet(0);

	public MemberPrivileges() {
	}

	public MemberPrivileges(int id, String privilegeName) {
		this.id = id;
		this.privilegeName = privilegeName;
	}

	public MemberPrivileges(int id, String privilegeName, Set memberses) {
		this.id = id;
		this.privilegeName = privilegeName;
		this.memberses = memberses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPrivilegeName() {
		return this.privilegeName;
	}

	public void setPrivilegeName(String privilegeName) {
		this.privilegeName = privilegeName;
	}

	public Set getMemberses() {
		return this.memberses;
	}

	public void setMemberses(Set memberses) {
		this.memberses = memberses;
	}

}
