package cht.eric.models;
// Generated 2023年6月19日 下午2:30:18 by Hibernate Tools 6.1.7.Final

import java.sql.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private String id;
	private Date orderDate;
	private Date shipDate;
	private String shipMode;
	private String customerIdNumber;
	private String customerName;
	private String segment;
	private String country;
	private String city;
	private String state;
	private int postalCode;
	private String region;
	private String productIdNumber;
	private String category;
	private String subCategory;
	private String productName;
	private double sales;
	private int quantity;
	private float discount;
	private double profit;
	private boolean isReturned;

	public Orders() {
	}

	public Orders(String id, Date orderDate, Date shipDate, String shipMode, String customerIdNumber,
			String customerName, String segment, String country, String city, String state, int postalCode,
			String region, String productIdNumber, String category, String subCategory, String productName,
			double sales, int quantity, float discount, double profit, boolean isReturned) {
		this.id = id;
		this.orderDate = orderDate;
		this.shipDate = shipDate;
		this.shipMode = shipMode;
		this.customerIdNumber = customerIdNumber;
		this.customerName = customerName;
		this.segment = segment;
		this.country = country;
		this.city = city;
		this.state = state;
		this.postalCode = postalCode;
		this.region = region;
		this.productIdNumber = productIdNumber;
		this.category = category;
		this.subCategory = subCategory;
		this.productName = productName;
		this.sales = sales;
		this.quantity = quantity;
		this.discount = discount;
		this.profit = profit;
		this.isReturned = isReturned;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

	public String getShipMode() {
		return this.shipMode;
	}

	public void setShipMode(String shipMode) {
		this.shipMode = shipMode;
	}

	public String getCustomerIdNumber() {
		return this.customerIdNumber;
	}

	public void setCustomerIdNumber(String customerIdNumber) {
		this.customerIdNumber = customerIdNumber;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getSegment() {
		return this.segment;
	}

	public void setSegment(String segment) {
		this.segment = segment;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getProductIdNumber() {
		return this.productIdNumber;
	}

	public void setProductIdNumber(String productIdNumber) {
		this.productIdNumber = productIdNumber;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getSubCategory() {
		return this.subCategory;
	}

	public void setSubCategory(String subCategory) {
		this.subCategory = subCategory;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public double getSales() {
		return this.sales;
	}

	public void setSales(double sales) {
		this.sales = sales;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public float getDiscount() {
		return this.discount;
	}

	public void setDiscount(float discount) {
		this.discount = discount;
	}

	public double getProfit() {
		return this.profit;
	}

	public void setProfit(double profit) {
		this.profit = profit;
	}

	public boolean isIsReturned() {
		return this.isReturned;
	}

	public void setIsReturned(boolean isReturned) {
		this.isReturned = isReturned;
	}

}
