/*
 * This file is generated by jOOQ.
 */
package cht.eric.models;


import cht.eric.models.tables.Member;
import cht.eric.models.tables.MemberMemberPrivilegeRelation;
import cht.eric.models.tables.MemberPrivilege;
import cht.eric.models.tables.Order;
import cht.eric.models.tables.User;


/**
 * Convenience access to all tables in cht_newcomer_training.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cht_newcomer_training.member</code>.
     */
    public static final Member MEMBER = Member.MEMBER;

    /**
     * The table
     * <code>cht_newcomer_training.member_member_privilege_relation</code>.
     */
    public static final MemberMemberPrivilegeRelation MEMBER_MEMBER_PRIVILEGE_RELATION = MemberMemberPrivilegeRelation.MEMBER_MEMBER_PRIVILEGE_RELATION;

    /**
     * The table <code>cht_newcomer_training.member_privilege</code>.
     */
    public static final MemberPrivilege MEMBER_PRIVILEGE = MemberPrivilege.MEMBER_PRIVILEGE;

    /**
     * The table <code>cht_newcomer_training.order</code>.
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * The table <code>cht_newcomer_training.user</code>.
     */
    public static final User USER = User.USER;
}
