package cht.eric.models;
// Generated 2023年6月19日 下午2:30:18 by Hibernate Tools 6.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int id;
	private String account;
	private String password;
	private Set memberses = new HashSet(0);

	public Users() {
	}

	public Users(int id, String account, String password) {
		this.id = id;
		this.account = account;
		this.password = password;
	}

	public Users(int id, String account, String password, Set memberses) {
		this.id = id;
		this.account = account;
		this.password = password;
		this.memberses = memberses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getMemberses() {
		return this.memberses;
	}

	public void setMemberses(Set memberses) {
		this.memberses = memberses;
	}

}
