/*
 * This file is generated by jOOQ.
 */
package cht.eric.models.cht_newcomer_training.tables.pojos;


import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "members_member_privileges_relations",
    schema = "cht_newcomer_training"
)
public class MembersMemberPrivilegesRelations implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer memberId;
    private Integer memberPrivilegeId;

    public MembersMemberPrivilegesRelations() {}

    public MembersMemberPrivilegesRelations(MembersMemberPrivilegesRelations value) {
        this.memberId = value.memberId;
        this.memberPrivilegeId = value.memberPrivilegeId;
    }

    public MembersMemberPrivilegesRelations(
        Integer memberId,
        Integer memberPrivilegeId
    ) {
        this.memberId = memberId;
        this.memberPrivilegeId = memberPrivilegeId;
    }

    /**
     * Getter for
     * <code>cht_newcomer_training.members_member_privileges_relations.member_id</code>.
     */
    @Column(name = "member_id", nullable = false)
    @NotNull
    public Integer getMemberId() {
        return this.memberId;
    }

    /**
     * Setter for
     * <code>cht_newcomer_training.members_member_privileges_relations.member_id</code>.
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * Getter for
     * <code>cht_newcomer_training.members_member_privileges_relations.member_privilege_id</code>.
     */
    @Column(name = "member_privilege_id", nullable = false)
    @NotNull
    public Integer getMemberPrivilegeId() {
        return this.memberPrivilegeId;
    }

    /**
     * Setter for
     * <code>cht_newcomer_training.members_member_privileges_relations.member_privilege_id</code>.
     */
    public void setMemberPrivilegeId(Integer memberPrivilegeId) {
        this.memberPrivilegeId = memberPrivilegeId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MembersMemberPrivilegesRelations other = (MembersMemberPrivilegesRelations) obj;
        if (this.memberId == null) {
            if (other.memberId != null)
                return false;
        }
        else if (!this.memberId.equals(other.memberId))
            return false;
        if (this.memberPrivilegeId == null) {
            if (other.memberPrivilegeId != null)
                return false;
        }
        else if (!this.memberPrivilegeId.equals(other.memberPrivilegeId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.memberId == null) ? 0 : this.memberId.hashCode());
        result = prime * result + ((this.memberPrivilegeId == null) ? 0 : this.memberPrivilegeId.hashCode());
        return result;
    }
}
