/*
 * This file is generated by jOOQ.
 */
package cht.eric.models.cht_newcomer_training.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum OrdersSegment implements EnumType {

    Consumer("Consumer"),

    Corporate("Corporate"),

    Home_Office("Home Office");

    private final String literal;

    private OrdersSegment(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static OrdersSegment lookupLiteral(String literal) {
        return EnumType.lookupLiteral(OrdersSegment.class, literal);
    }
}
