/*
 * This file is generated by jOOQ.
 */
package cht.eric.models.cht_newcomer_training;


import cht.eric.models.cht_newcomer_training.tables.MemberPrivileges;
import cht.eric.models.cht_newcomer_training.tables.Members;
import cht.eric.models.cht_newcomer_training.tables.MembersMemberPrivilegesRelations;
import cht.eric.models.cht_newcomer_training.tables.Orders;
import cht.eric.models.cht_newcomer_training.tables.Users;


/**
 * Convenience access to all tables in cht_newcomer_training.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cht_newcomer_training.member_privileges</code>.
     */
    public static final MemberPrivileges MEMBER_PRIVILEGES = MemberPrivileges.MEMBER_PRIVILEGES;

    /**
     * The table <code>cht_newcomer_training.members</code>.
     */
    public static final Members MEMBERS = Members.MEMBERS;

    /**
     * The table
     * <code>cht_newcomer_training.members_member_privileges_relations</code>.
     */
    public static final MembersMemberPrivilegesRelations MEMBERS_MEMBER_PRIVILEGES_RELATIONS = MembersMemberPrivilegesRelations.MEMBERS_MEMBER_PRIVILEGES_RELATIONS;

    /**
     * The table <code>cht_newcomer_training.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>cht_newcomer_training.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
