/*
 * This file is generated by jOOQ.
 */
package cht.eric.models.tables;


import cht.eric.models.ChtNewcomerTraining;
import cht.eric.models.Keys;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberMemberPrivilegeRelation extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>cht_newcomer_training.member_member_privilege_relation</code>
     */
    public static final MemberMemberPrivilegeRelation MEMBER_MEMBER_PRIVILEGE_RELATION = new MemberMemberPrivilegeRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column
     * <code>cht_newcomer_training.member_member_privilege_relation.member_id</code>.
     */
    public final TableField<Record, Integer> MEMBER_ID = createField(DSL.name("member_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>cht_newcomer_training.member_member_privilege_relation.member_privilege_id</code>.
     */
    public final TableField<Record, Integer> MEMBER_PRIVILEGE_ID = createField(DSL.name("member_privilege_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private MemberMemberPrivilegeRelation(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private MemberMemberPrivilegeRelation(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased
     * <code>cht_newcomer_training.member_member_privilege_relation</code> table
     * reference
     */
    public MemberMemberPrivilegeRelation(String alias) {
        this(DSL.name(alias), MEMBER_MEMBER_PRIVILEGE_RELATION);
    }

    /**
     * Create an aliased
     * <code>cht_newcomer_training.member_member_privilege_relation</code> table
     * reference
     */
    public MemberMemberPrivilegeRelation(Name alias) {
        this(alias, MEMBER_MEMBER_PRIVILEGE_RELATION);
    }

    /**
     * Create a
     * <code>cht_newcomer_training.member_member_privilege_relation</code> table
     * reference
     */
    public MemberMemberPrivilegeRelation() {
        this(DSL.name("member_member_privilege_relation"), null);
    }

    public <O extends Record> MemberMemberPrivilegeRelation(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, MEMBER_MEMBER_PRIVILEGE_RELATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ChtNewcomerTraining.CHT_NEWCOMER_TRAINING;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_MEMBER_MEMBER_PRIVILEGE_RELATION_PRIMARY;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.FK_MEMBERS_MEMBER_PRIVILEGES_RELATIONS_MEMBERS, Keys.FK_MEMBERS_MEMBER_PRIVILEGES_RELATIONS_MEMBER_PRIVILEGES);
    }

    private transient Member _member;
    private transient MemberPrivilege _memberPrivilege;

    /**
     * Get the implicit join path to the
     * <code>cht_newcomer_training.member</code> table.
     */
    public Member member() {
        if (_member == null)
            _member = new Member(this, Keys.FK_MEMBERS_MEMBER_PRIVILEGES_RELATIONS_MEMBERS);

        return _member;
    }

    /**
     * Get the implicit join path to the
     * <code>cht_newcomer_training.member_privilege</code> table.
     */
    public MemberPrivilege memberPrivilege() {
        if (_memberPrivilege == null)
            _memberPrivilege = new MemberPrivilege(this, Keys.FK_MEMBERS_MEMBER_PRIVILEGES_RELATIONS_MEMBER_PRIVILEGES);

        return _memberPrivilege;
    }

    @Override
    public MemberMemberPrivilegeRelation as(String alias) {
        return new MemberMemberPrivilegeRelation(DSL.name(alias), this);
    }

    @Override
    public MemberMemberPrivilegeRelation as(Name alias) {
        return new MemberMemberPrivilegeRelation(alias, this);
    }

    @Override
    public MemberMemberPrivilegeRelation as(Table<?> alias) {
        return new MemberMemberPrivilegeRelation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MemberMemberPrivilegeRelation rename(String name) {
        return new MemberMemberPrivilegeRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MemberMemberPrivilegeRelation rename(Name name) {
        return new MemberMemberPrivilegeRelation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MemberMemberPrivilegeRelation rename(Table<?> name) {
        return new MemberMemberPrivilegeRelation(name.getQualifiedName(), null);
    }
}
