/*
 * This file is generated by jOOQ.
 */
package org.jooq.your.packagename.cht_newcomer_training.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum OrdersShipMode implements EnumType {

    First_Class("First Class"),

    Second_Class("Second Class"),

    Standard_Class("Standard Class"),

    Same_Day("Same Day");

    private final String literal;

    private OrdersShipMode(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static OrdersShipMode lookupLiteral(String literal) {
        return EnumType.lookupLiteral(OrdersShipMode.class, literal);
    }
}
